### ISSUE TITLE
После последнего изменения перестало работать

### ISSUE THREAD

**Issue by AngryGantz** [alexusmai/ruslug#1]
Сегодня апдейтил композер, перестал работать Slug. Ошибок не выбрасывает, но возвращает пустую строку.
в функции make($title)
Закомментировал 

//            "«" => "",
//            "»" => "",
//            "№" => "",
//            "Ӏ" => "",
//            "’" => "",
//            "ˮ" => "",
//            "_" => "-",
//            "'" => "",
//            "`" => "",
//            "^" => "",
//            "." => "",
//            ',' => "",
//            ':' => "",
//            '"' => "",
//            "<" => "",
//            ">" => ""

заработало. Laravel 5.1

**Comment by alexusmai** [comment]
Спасибо, исправил, проблема была  тут

```
"." => "",

а надо так

"\." => "",
```
