### ISSUE TITLE
Non-static method Alexusmai\Ruslug\Slug::make() should not be called statically

### ISSUE THREAD

**Issue by Scronheim** [alexusmai/ruslug#2]
Думаю из ошибки все ясно

**Comment by alexusmai** [comment]
Все работает.
Пробуем!

`
Route::get('/', function () {
    $text = 'Ура заработало!';
    dd(Slug::make($text));
});
`

а теперь пробуем так:

`
Route::get('/', function () {
    $text = 'А теперь не работает!';
   dd(\Alexusmai\Ruslug\Slug::make($text));
});
`
И получаем ошибку.. 
Документация по фасадам на русском - https://laravel.ru/docs/v5/facades
