### ISSUE TITLE
Добавить удаление спецсимволов

### ISSUE THREAD

**Issue by bigperson** [alexusmai/ruslug#6]
Хорошо было бы иметь возможность удалять спецсимволы `().!"№;%:?...` _ заменять на -

**Comment by alexusmai** [comment]
Привет.
В принципе пакет уже устарел, и не имеет смысла. Laravel умеет уже делать это сам... с какой версии он научился это делать не помню.. но вроде уже давно.

Str::slug() - подробнее в [документации](https://laravel.com/docs/5.7/helpers#method-str-slug)
